version: '3.8'
services:
  nginx:
    volumes:
      - .:/app
    ports:
      - 8080:80
  app:
    volumes:
      - .:/app
  database:
    volumes:
      - database-data:/var/lib/mysql
    ports:
      - 3307:3306
  adminer:
    ports:
      - 8082:8080