version: '3.8'
services:
  nginx:
    image: nginx:latest
    depends_on:
      - app
    environment:
      - DOCROOT=/app/public
  app:
    build: docker/PHP
    depends_on:
      - database
  database:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
  adminer:
    image: adminer
    depends_on:
      - database
    environment:
      - ADMINER_DEFAULT_SERVER=database
      - ADMINER_DESIGN=brade

volumes:
  database-data: {}